### ISSUE TITLE
No sound on latest version from Snap Store

### ISSUE THREAD

**Issue by jonrandy** [mmartinortiz/retro-virtual-machine-snap#1]
There appears to be no sound on the latest version in the Snap Store. I see that a recent commit appears to address this - any chance it will be updated in the store soon?

**Comment by jonrandy** [comment]
Now at 2.1.3 - still no sound :(

**Comment by jonrandy** [comment]
2.1.4 appears to be working... thanks!

**Comment by mmartinortiz** [comment]
Hi @jonrandy , I'd like to apologize for my lack of response. I just realised that my email notifications were disable, so I never knew until now about your issue. As you saw, it was already solved for the 2.1.4 version of retro virtual machine :-)
